{
    'name': "Ejad Account",
    'version': '15.0.0.1',
    'depends': [
        'base',
        'account_invoicing',
    ],
    'author': "CVC",
    'description': """
    """,
    'depends': ['base_setup', 'sale', 'hr', 'account', 'base'],
    'data': [
        'data/product_category_data.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'wizards/account_financial_report_wizard.xml',
        'wizards/partner_receivable_ledger_wizard.xml',
        'wizards/training_financial_report_Wizard.xml',
        'wizards/payment_cancel_wizard.xml',
        'wizards/payment_reset_draft_wizard.xml',
        'wizards/refund_invoice_report_wizard.xml',
        'wizards/bank_letter_multi_wizard.xml',
        'wizards/payment_order_report_wizard.xml',
        'view/account_invoice_line_view.xml',
        'view/payment.xml',
        'view/res_partner_view.xml',
        'view/account_invoice.xml',
        'view/account_move_view.xml',
        'view/account_invoice_multi_partners.xml',
        'data/sequence.xml',
        'view/reverse_entry_request_view.xml',
        'view/account_journal_dashboard_view.xml',
        'view/view_account_account_category.xml',
        'view/view_account_accounts.xml',
        # 'report/total_credit_debit_report.xml',
        'report/internal_layout.xml',
        'report/report_payment_receipt1.xml',
        'report/report_payment_receipt2.xml',
        'report/partner_receivable_ledger.xml',
        'report/account_financial_reports.xml',
        'report/training_financial_report.xml',
        'report/bank_letter_report.xml',
        'report/res_company_conf.xml',
        'report/account_report.xml',
        'report/bank_letter_multi.xml',
        'report/account_invoice_report.xml',
        'report/refund_invoice_report.xml',
        'report/payment_order_report.xml',

    ],
}
