# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Ejad Backend Theme (For Community Edition)',
    'category': "Themes/Backend",
    'version': '1.0',
    'license': 'OPL-1',
    'summary': 'Flexible, Powerful and Fully Responsive Customized Backend Theme with many features(Favorite Bar, Vertical Horizontal Menu Bar, Night Mode, Tree view of Menu and Sub menu, Fuzzy search for apps, Display density) in Community Edition.',
    'description': """ Flexible, Powerful and Fully Responsive Customized Backend Theme with many features(Favorite Bar,
    """,
    'author': 'Synconics Technologies Pvt. Ltd.',
    'depends': ['web', 'web_editor', 'mail'],
    'website': 'www.synconics.com',
    'data': [
        'data/theme_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/web_layout_custom.xml',
        'views/ir_module_views.xml',
    ],
    'images': [
        'static/description/main_screen.png',
        'static/description/ejad_screenshot.png',
    ],
     'assets': {
        'web.assets_common':[
            '/ehab_backend_theme/static/src/js/freamwork/config.js',
        ],
        'web._assets_primary_variables' :    [
            # <!-- link scss variables-->
            "ehab_backend_theme/static/src/scss/variables.scss",
            "ehab_backend_theme/static/src/scss/other_variable.scss",
            "ehab_backend_theme/static/src/scss/night_mode/ni_variables.scss",
        ],
        'web.assets_backend': [
            # <!-- Layout File - Start-->
            "/ehab_backend_theme/static/src/lib/minicolors/jquery.minicolors.css",
            "/ehab_backend_theme/static/src/scss/animation.scss",
            "/ehab_backend_theme/static/src/scss/fonts.scss",
            "/ehab_backend_theme/static/src/scss/light_mode/light_mode.scss",
            # Home Menu
            "/ehab_backend_theme/static/src/scss/layout/home_menu/home_menu.scss",
            # Left panel
            "/ehab_backend_theme/static/src/scss/layout/left_panel/left_menu_horizontal.scss",
            "/ehab_backend_theme/static/src/scss/layout/left_panel/left_menu_vertical.scss",
            "/ehab_backend_theme/static/src/scss/layout/left_panel/left_menu.scss",
            "/ehab_backend_theme/static/src/scss/layout/left_panel/theme_customize_model.scss",
            #control panel
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_panel_search.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_search_options.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_action_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_panel_top.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_panel_bottom.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_panel_model.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/control_panel.scss",
            "/ehab_backend_theme/static/src/scss/layout/control_panel/search_panel.scss",
            # kanban view
            "/ehab_backend_theme/static/src/scss/layout/kanban/group_kanban.scss",
            "/ehab_backend_theme/static/src/scss/layout/kanban/ungroup_kanban.scss",
            "/ehab_backend_theme/static/src/scss/layout/kanban/kanban_model.scss",
            "/ehab_backend_theme/static/src/scss/layout/kanban/kanban_view.scss",
            #List View
            "/ehab_backend_theme/static/src/scss/layout/list/list_view.scss",
            #calendar view
            "/ehab_backend_theme/static/src/scss/layout/calendar/calendar_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/calendar/web_calender.scss",
            # activity view
            "/ehab_backend_theme/static/src/scss/layout/activity/activity_view.scss",
            # pivot view
            "/ehab_backend_theme/static/src/scss/layout/pivot/pivot_view.scss",
            #discuss
            "/ehab_backend_theme/static/src/scss/layout/discuss/composer_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/discuss/message_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/discuss/video_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/discuss/mailbox_mail.scss",
            "/ehab_backend_theme/static/src/scss/layout/discuss/chat_view.scss",
            # Form view
            "/ehab_backend_theme/static/src/scss/layout/form/form_statusbar.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/button_box.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/notbook_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/form_view_mixin.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/form_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/form_model.scss",
            "/ehab_backend_theme/static/src/scss/layout/form/setting_view.scss",
            # Graph view
            "/ehab_backend_theme/static/src/scss/layout/graph/graph_view.scss",
            # Import view
            "/ehab_backend_theme/static/src/scss/layout/import/import_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/import/select_drop.scss",
            #App
            "/ehab_backend_theme/static/src/scss/layout/app/expense_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/app/hr_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/app/lunch_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/app/purchase_view.scss",
            #core
            "/ehab_backend_theme/static/src/scss/layout/core/loading.scss",
            "/ehab_backend_theme/static/src/scss/layout/core/error_message_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/core/nocontent_view.scss",
            "/ehab_backend_theme/static/src/scss/layout/core/signout_layout.scss",
            "/ehab_backend_theme/static/src/scss/layout/core/effects.scss",
            "/ehab_backend_theme/static/src/scss/layout/web_client.scss",
            "/ehab_backend_theme/static/src/scss/layout/layout.scss",
            # <!-- Responsive -->
            #left_panel
            "/ehab_backend_theme/static/src/scss/responsive/left_panel/left_menu.scss",
            #app
            "/ehab_backend_theme/static/src/scss/responsive/app/r_hr_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/home_menu.scss",
            "/ehab_backend_theme/static/src/scss/responsive/chat_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/control_panel_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/kanban_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/list_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/form_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/configration.scss",
            "/ehab_backend_theme/static/src/scss/responsive/mail_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/pivot_view.scss",
            "/ehab_backend_theme/static/src/scss/responsive/base_settings.scss",
            "/ehab_backend_theme/static/src/scss/responsive/responsive_xs.scss",
            # <!-- Rtl -->
            "/ehab_backend_theme/static/src/scss/rtl/rtl.scss",
            # <!-- Lib -->
            "/ehab_backend_theme/static/src/lib/custom_radiobutton.scss",
            "/ehab_backend_theme/static/src/lib/custom_checkbox.scss",
            # <!-- NI mode -->
            "/ehab_backend_theme/static/src/scss/night_mode/freamwork/ni_control_panel.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/freamwork/ni_header_layout.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_home_menu.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_kanban_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_list_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_graph_layout.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_activity_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_barcode_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_pivot_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_calander_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_mail_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_gernal_setting_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_dashboards_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_form_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_model_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_import_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_window_chnage_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_attendance_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_lunch_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/views/ni_purchase_view.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/ni_common_layout.scss",
            "/ehab_backend_theme/static/src/scss/night_mode/ni_layout.scss",
            "/ehab_backend_theme/static/src/scss/all.css",
            "/ehab_backend_theme/static/src/scss/custom.scss",
            "/ehab_backend_theme/static/src/scss/media.scss",

            # <!-- JS Path - start -->
            "/ehab_backend_theme/static/src/js/ejad_web_themes.js",
            "/ehab_backend_theme/static/src/lib/minicolors/jquery.minicolors.min.js",
            "/ehab_backend_theme/static/src/js/main_view.js",
            "/ehab_backend_theme/static/src/js/views/res_config_settings.js",
            "/ehab_backend_theme/static/src/js/views/menu.js",
            "/ehab_backend_theme/static/src/js/chrome/error_handlers.js",
            "/ehab_backend_theme/static/src/js/components/chat_window/chat_window.js",
            "/ehab_backend_theme/static/src/js/components/action_menus.js",
            "/ehab_backend_theme/static/src/js/components/dropdown_navigation_hook.js",
            "/ehab_backend_theme/static/src/js/components/dropdown_menu.js",
            "/ehab_backend_theme/static/src/js/components/dropdown.js",
            "/ehab_backend_theme/static/src/js/views/control_panel/control_panel.js",
            "/ehab_backend_theme/static/src/js/views/control_panel/control_panel_ext.js",
            "/ehab_backend_theme/static/src/js/views/control_panel/search_bar.js",
            "/ehab_backend_theme/static/src/js/search/search_panel.js",
            "/ehab_backend_theme/static/src/js/search/search_bar/search_bar.js",
            "/ehab_backend_theme/static/src/js/webclient/navbar/navbar.js",
            "/ehab_backend_theme/static/src/js/webclient/navbar/systray_activity_menu.js",
            "/ehab_backend_theme/static/src/js/webclient/menubar.js",
            "/ehab_backend_theme/static/src/js/webclient/favorite_menu_view.js",
            "/ehab_backend_theme/static/src/js/webclient/action_service.js",
            "/ehab_backend_theme/static/src/js/webclient/webclient.js",
            "/ehab_backend_theme/static/src/js/webclient/custom_menu/custom_menu.js",
            "/ehab_backend_theme/static/src/js/webclient/custom_menu/menus/menu_helpers.js",
            "/ehab_backend_theme/static/src/js/services/systray_hepler.js",
            "/ehab_backend_theme/static/src/js/views/search_panel_mobile.js",
            "/ehab_backend_theme/static/src/js/views/form/form_renderer.js",
            "/ehab_backend_theme/static/src/js/views/list/list_model.js",
            "/ehab_backend_theme/static/src/js/views/list/list_controller.js",
            "/ehab_backend_theme/static/src/js/views/list/list_renderer.js",
            "/ehab_backend_theme/static/src/js/views/list/list_view.js",
            "/ehab_backend_theme/static/src/js/views/kanban/kanban_column_quick_create_mobile.js",
            "/ehab_backend_theme/static/src/js/views/kanban/kanban_controller.js",
            "/ehab_backend_theme/static/src/js/views/kanban/kanban_renderer_mobile.js",
            "/ehab_backend_theme/static/src/js/views/kanban/kanban_view.js",
            "/ehab_backend_theme/static/src/js/views/graph/color.js",
            "/ehab_backend_theme/static/src/js/views/graph/graph_renderer.js",
            "/ehab_backend_theme/static/src/js/freamwork/dashboard.js",
            "/ehab_backend_theme/static/src/js/views/import_action.js",
            "/ehab_backend_theme/static/src/js/core/dialog.js",
            "/ehab_backend_theme/static/src/js/core/block_ui.js",
            "/ehab_backend_theme/static/src/js/fields/relational_fields.js",
            "/ehab_backend_theme/static/src/js/fields/basic_fields.js",
            "/ehab_backend_theme/static/src/js/responsive/breadcrumb.js",
            "/ehab_backend_theme/static/src/js/plugins.js",
        ],
        'web.assets_backend_prod_only': [
            ('replace', 'web_enterprise/static/src/main.js', '/ehab_backend_theme/static/src/js/main.js'),
        ],
        'web.assets_qweb': [
            'ehab_backend_theme/static/src/xml/*.xml',
            'ehab_backend_theme/static/src/xml/**/*.xml',
        ],
    },
    'post_init_hook': 'post_init_check',
    'uninstall_hook': 'uninstall_hook',
    'price': 400.0,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'bootstrap': True,
}