{
    'name': 'Ejad HR',
    'version': '13.0.1.0.0',
    'category': 'Human Resources',
    'description': """
    """,
    'author': 'CVC',
    'website': '',
    'depends': [
        'ejad_erp_base',
        'ejad_erp_account',
        'documents',
        'stock',
        'hr',
        'hr_contract',
        'hr_recruitment',
        'hr_holidays',
        'hr_payroll',
        'hr_attendance',
        'resource',
        'report_xlsx',
    ],
    'data': [
        'data/dynamic_workflow_beneficiary_data.xml',
        'data/dynamic_workflow_stage_data.xml',
        'data/dynamic_workflow_secondary_category_data.xml',
        'data/dynamic_workflow_principal_category_data.xml',
        'data/dynamic_workflow_project_type_data.xml',
        'data/mail_template.xml',

        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/hr_salary_template_report_pdf.xml',
        'wizards/mandate_payment_wizard.xml',
        'wizards/endofservices_wizard.xml',
        'wizards/bank_letter_wizard.xml',
        'wizards/bank_letter_payroll_wizard.xml',
        'wizards/return_remaining_loan_wizard.xml',
        'wizards/payroll_excel_sheet.xml',
        'wizards/dynamic_workflow_stage_previous_wizard.xml',
        'wizards/dynamic_workflow_refuse_reason.xml',
        'wizards/dynamic_workflow_return_reason.xml',
        'wizards/refuse_reason_leave.xml',
        'wizards/refuse_reason_leave_return.xml',

        'reports/employee_custody_report.xml',
        'views/res_config_endservice.xml',
        'views/employee_custody_view.xml',
        'views/employee_mandate_config_view.xml',
        'views/employee_permissions_config_view.xml',
        'views/employee_mandate_request_view.xml',
        'views/hr_department_view.xml',

        'data/employee_custody_sequence.xml',
        'data/automate_action.xml',
        'data/saudi_cities.xml',
        'data/hr_recruitment_stage.xml',

        'views/dynamic_workflow_stage.xml',
        'views/dynamic_workflow_project_type_views.xml',

        'views/hr_applicant_views.xml',
        'views/hr_contract_history.xml',
        'views/employee_qualification_config.xml',
        'views/hr.xml',
        'views/hr_grade.xml',
        'views/contract_alarm.xml',
        'views/hr_deductions.xml',
        'views/hr_loan.xml',
        'views/hr_holiday.xml',
        'data/holiday_scheduler.xml',
        'data/hr_payroll.xml',
        'data/salary_rule_data.xml',
        'data/salary_bonus_scheduler.xml',
        'views/hr_setting_view.xml',
        'views/employee_promotion_view.xml',

        "views/attendace_record_wizard.xml",
        'views/hr_attendance_view.xml',
        'data/attendance_record_scheduler.xml',
        'views/hr_job.xml',
        'views/hr_endofservice.xml',
        'views/deduction_reward_view.xml',
        'views/hr_salary_template.xml',
        'views/validate_salary_qrcode.xml',
        'views/hr_holiday_return.xml',
        # reports

        'reports/custody_reports.xml',
        'reports/employee_custody_barcode_views.xml',
        'reports/bank_letter_report.xml',
        'reports/bank_letter_payroll_report.xml',
        'reports/print_leave_report.xml',

        'views/hr_payroll_account.xml',
        'views/hr_payslip_view.xml',
        'views/hr_payroll_advice.xml',
        'views/connect_mssql.xml',

    ],
    'sequence': 1,
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'Other proprietary'
}
